name: CI Formatting & Linting

on:
  pull_request:
    types: [opened, reopened, synchronize]


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Install extra dependencies for a python install
        run: |
          sudo apt-get update
          sudo apt -y install --no-install-recommends liblzma-dev libbz2-dev libreadline-dev

      - name: Install asdf cli
        uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47

      - name: Install software through asdf
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47
      
      - name: reshim asdf
        run: asdf reshim
      
      - name: ensure poetry using desired python version
        run: poetry env use $(asdf which python)

      - name: Install lint dependencies
        run: |
          poetry install --sync --no-interaction --with lint
      
      - name: Run black
        run: poetry run black src

      - name: Run isort
        run: poetry run isort src

      - name: Run mypy
        run: poetry run mypy src

      - name: Run pylint
        run: poetry run pylint src